#!/bin/bash
# ============================================================
# Script de mise à jour email admin et test
# ============================================================

echo "🔧 MISE À JOUR EMAIL ADMIN - admin@rombat.com → admin1@rombat.com"
echo ""
echo "📋 ÉTAPES À SUIVRE:"
echo ""
echo "1️⃣ ÉTAPE 1: Aller dans Supabase SQL Editor"
echo "   - URL: https://app.supabase.com/project/kuluihwgrppsziezqrws/sql/new"
echo "   - Ou via Supabase Dashboard > SQL Editor > New Query"
echo ""
echo "2️⃣ ÉTAPE 2: Copier-coller le script SQL ci-dessous"
echo ""
echo "================== DÉBUT DU SCRIPT SQL =================="
echo ""
echo "-- Vérifier l'utilisateur admin actuel"
echo "SELECT id, email FROM auth.users WHERE email = 'admin@rombat.com';"
echo ""
echo "-- Mettre à jour l'email"
echo "UPDATE auth.users"
echo "SET email = 'admin1@rombat.com',"
echo "    email_confirmed_at = NOW()"
echo "WHERE email = 'admin@rombat.com';"
echo ""
echo "-- Vérifier la mise à jour"
echo "SELECT id, email FROM auth.users WHERE email = 'admin1@rombat.com';"
echo ""
echo "-- Afficher tous les utilisateurs"
echo "SELECT u.id, u.email, p.full_name, p.role"
echo "FROM auth.users u"
echo "LEFT JOIN profiles p ON u.id = p.id"
echo "ORDER BY u.created_at DESC;"
echo ""
echo "================== FIN DU SCRIPT SQL =================="
echo ""
echo "3️⃣ ÉTAPE 3: Exécuter le script (Ctrl+Enter)"
echo ""
echo "4️⃣ ÉTAPE 4: Vérifier les résultats"
echo "   - L'email doit être changé en admin1@rombat.com"
echo "   - Le profil doit être lié correctement"
echo ""
echo "5️⃣ ÉTAPE 5: Tester la connexion dans l'application"
echo "   - URL: http://localhost:5173 (ou votre URL)"
echo "   - Email: admin1@rombat.com"
echo "   - Mot de passe: Admin@2026!"
echo ""
echo "6️⃣ ÉTAPE 6: Tester la création de compte"
echo "   - Créer un nouvel utilisateur"
echo "   - Vérifier que tout fonctionne correctement"
echo ""
echo "7️⃣ ÉTAPE 7: Pousser sur GitHub"
echo "   - git add ."
echo "   - git commit -m 'Update: Change admin email to admin1@rombat.com'"
echo "   - git push origin main"
echo ""
echo "✅ DONE!"
